Check db.conf exists, otherwise copy it

diff --git a/backup-db b/backup-db
--- a/backup-db
+++ b/backup-db
@@ -1,6 +1,13 @@
 #!/bin/bash
 # backup-db: Backup a database.
 
+if [[ ! -z "${BASH_SOURCE%/*}/db.conf" ]]; then
+    echo "Configuration file missing. We just copied the example for you."
+    echo "Edit the db.conf file and re-run script."
+    cp "${BASH_SOURCE%/*}/db.conf.example" "${BASH_SOURCE%/*}/db.conf"
+  exit 1;
+fi
+
 . "${BASH_SOURCE%/*}/db.conf"
 
 if [ -z "$1" ]; then
diff --git a/clone-db b/clone-db
--- a/clone-db
+++ b/clone-db
@@ -1,11 +1,14 @@
 #!/bin/bash
 # clone-db: Clone a database into another database.
 
-echo ""
-echo "Processing '$0 $1 $2 $3'"
-echo ""
+if [[ ! -z "${BASH_SOURCE%/*}/db.conf" ]]; then
+    echo "Configuration file missing. We just copied the example for you."
+    echo "Edit the db.conf file and re-run script."
+    cp "${BASH_SOURCE%/*}/db.conf.example" "${BASH_SOURCE%/*}/db.conf"
+  exit 1;
+fi
 
-. db.conf
+. "${BASH_SOURCE%/*}/db.conf"
 
 if [ -z "$1" ] || [ -z "$2" ]; then
   echo "clone-db [source] [destination] [no backup]";
